GET http://localhost:8000/products/ HTTP/1.1

###
GET http://localhost:8000/products/4/ HTTP/1.1

###
DELETE http://localhost:8000/products/2/ HTTP/1.1

###
PUT http://localhost:8000/products/3/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1MTkwMTk2LCJpYXQiOjE3NjUxODk4OTYsImp0aSI6Ijc5NDUyY2NlMGVjYjRlMDFiMGJlZDUxNWZmNmYyZjU3IiwidXNlcl9pZCI6IjEifQ.aZdbl3nAEpd_Uxc6Grok6rDWtuwtrrP7CkvvQqcXdcw

{
    "name": "Television",
    "price": 300.00,
    "stock": 14,
    "description": "An amazing new TV"
}

###
POST http://localhost:8000/products/1/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1MTkwMTk2LCJpYXQiOjE3NjUxODk4OTYsImp0aSI6Ijc5NDUyY2NlMGVjYjRlMDFiMGJlZDUxNWZmNmYyZjU3IiwidXNlcl9pZCI6IjEifQ.aZdbl3nAEpd_Uxc6Grok6rDWtuwtrrP7CkvvQqcXdcw

{
    "name": "Television",
    "price": 300.00,
    "stock": 14,
    "description": "An amazing new TV"
}

###

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username" : "admin",
    "password": "test"
}

###

POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2NTI2NzYzNiwiaWF0IjoxNzY1MTgxMjM2LCJqdGkiOiJiODI1MzcyZDI0Njc0YjdlYmQ3ODUzZjQzMjVkMzMyMyIsInVzZXJfaWQiOiIxIn0.7OwngYoIandmySfRCDZpmnCVUiLG3Bfi8VM2mV-XMYs"
}

###

GET http://localhost:8000/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1NTM2NjAyLCJpYXQiOjE3NjU1MzYzMDIsImp0aSI6ImY3OWQ0ZTkwZWU5YjQyY2Q5ZDc2ZDQ1ZTZjMmIyMzE3IiwidXNlcl9pZCI6IjIifQ.rsOegN-wOqyWYIbwdriRq6rtUCUrJS2P00gV3ffZ_I4

###
GET http://localhost:8000/orders/40ef9cbc-b915-42e9-86d9-0b68eba65fa6 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1NTM2NjAyLCJpYXQiOjE3NjU1MzYzMDIsImp0aSI6ImY3OWQ0ZTkwZWU5YjQyY2Q5ZDc2ZDQ1ZTZjMmIyMzE3IiwidXNlcl9pZCI6IjIifQ.rsOegN-wOqyWYIbwdriRq6rtUCUrJS2P00gV3ffZ_I4

###
POST http://localhost:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1NTQ5NjM5LCJpYXQiOjE3NjU1NDkzMzksImp0aSI6IjI1NWFkYTlkNjZhYTQwZGViYjNhOTkwNmIwMmRjNWY5IiwidXNlcl9pZCI6IjEifQ.HkLvgDTrIx_Ap0-S_hfEZl8KjCpUbgq3-t_3d8OT74M

{ 
  "status": "Pending",
  "user": 2,
  "items": [
    {
        "product": 3,
        "quantity": 2
    },
    {
        "product": 5,
        "quantity": 1
    }
  ]
}
