GET http://localhost:8000/products/ HTTP/1.1

###
GET http://localhost:8000/products/4/ HTTP/1.1

###
DELETE http://localhost:8000/products/2/ HTTP/1.1

###
PUT http://localhost:8000/products/3/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1MTkwMTk2LCJpYXQiOjE3NjUxODk4OTYsImp0aSI6Ijc5NDUyY2NlMGVjYjRlMDFiMGJlZDUxNWZmNmYyZjU3IiwidXNlcl9pZCI6IjEifQ.aZdbl3nAEpd_Uxc6Grok6rDWtuwtrrP7CkvvQqcXdcw

{
    "name": "Television",
    "price": 300.00,
    "stock": 14,
    "description": "An amazing new TV"
}

###
POST http://localhost:8000/products/1/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1MTkwMTk2LCJpYXQiOjE3NjUxODk4OTYsImp0aSI6Ijc5NDUyY2NlMGVjYjRlMDFiMGJlZDUxNWZmNmYyZjU3IiwidXNlcl9pZCI6IjEifQ.aZdbl3nAEpd_Uxc6Grok6rDWtuwtrrP7CkvvQqcXdcw

{
    "name": "Television",
    "price": 300.00,
    "stock": 14,
    "description": "An amazing new TV"
}

###

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username" : "admin",
    "password": "test"
}

###

POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2NTI2NzYzNiwiaWF0IjoxNzY1MTgxMjM2LCJqdGkiOiJiODI1MzcyZDI0Njc0YjdlYmQ3ODUzZjQzMjVkMzMyMyIsInVzZXJfaWQiOiIxIn0.7OwngYoIandmySfRCDZpmnCVUiLG3Bfi8VM2mV-XMYs"
}

###

GET http://localhost:8000/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1NjMyMDQ0LCJpYXQiOjE3NjU2MzE3NDQsImp0aSI6IjQ1NTBjZDQwZWRjYzQ0YzA4NWJkMjhmNDVjYjkyZDRhIiwidXNlcl9pZCI6IjEifQ.uNDDQ9LgQUaF7DxTPY3gPgl7qae5zBTSRgeVcv-G1d4

###
GET http://localhost:8000/orders/c50cd8f3-0717-4699-a8fc-554b33feff60/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1NjMyMDQ0LCJpYXQiOjE3NjU2MzE3NDQsImp0aSI6IjQ1NTBjZDQwZWRjYzQ0YzA4NWJkMjhmNDVjYjkyZDRhIiwidXNlcl9pZCI6IjEifQ.uNDDQ9LgQUaF7DxTPY3gPgl7qae5zBTSRgeVcv-G1d4

###
POST http://localhost:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1NTUwOTIzLCJpYXQiOjE3NjU1NTA2MjMsImp0aSI6IjI4NTYwYjdmYmNmNTRmNzE5NWFkZTIxNjVhODZkOTFiIiwidXNlcl9pZCI6IjEifQ.DMlmbwBFWmt80eQrkIm6h-Zn2zfllovADcf5Vuz1P8Q

{ 
  "status": "Pending",
  "items": [
    {
        "product": 3,
        "quantity": 2
    },
    {
        "product": 5,
        "quantity": 1
    }
  ]
}


###
PUT http://localhost:8000/orders/40ef9cbc-b915-42e9-86d9-0b68eba65fa6/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1NjMyMDQ0LCJpYXQiOjE3NjU2MzE3NDQsImp0aSI6IjQ1NTBjZDQwZWRjYzQ0YzA4NWJkMjhmNDVjYjkyZDRhIiwidXNlcl9pZCI6IjEifQ.uNDDQ9LgQUaF7DxTPY3gPgl7qae5zBTSRgeVcv-G1d4

{
    "status": "Confirmed",
    "items": [
        {
            "product": 4,
            "quantity": 5
        },
        {
            "product": 5,
            "quantity": 5
        }
    ]
}


###
DELETE http://localhost:8000/orders/c50cd8f3-0717-4699-a8fc-554b33feff60/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1NjMyMDQ0LCJpYXQiOjE3NjU2MzE3NDQsImp0aSI6IjQ1NTBjZDQwZWRjYzQ0YzA4NWJkMjhmNDVjYjkyZDRhIiwidXNlcl9pZCI6IjEifQ.uNDDQ9LgQUaF7DxTPY3gPgl7qae5zBTSRgeVcv-G1d4